service: api

provider:
  name: google
  stage: dev
  runtime: python37
  region: us-east4
  project: snoo-api
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/keyfile.json
plugins:
  - serverless-google-cloudfunctions
  - serverless-python-requirements
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
custom:
  pythonRequirements:
    usePipenv: true
functions:
  snoo-api:
    handler: event
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project, ""}/topics/${self:provider.project, "-topic"}'
